<a href="https://colab.research.google.com/github/anirudhjbabu1/nifty50-stock-market-prediction-using-LSTM/blob/main/nifty50.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Stock Market prediction using lstm



In [ ]:
import pandas as pd

In [ ]:
import pandas_datareader as pdr

In [ ]:
df=pd.read_csv('/content/ADANIPORTS.csv')

In [ ]:
df.head()

Date      Symbol Series  Prev Close    Open     High    Low   Last  \
0  2007-11-27  MUNDRAPORT     EQ      440.00  770.00  1050.00  770.0  959.0   
1  2007-11-28  MUNDRAPORT     EQ      962.90  984.00   990.00  874.0  885.0   
2  2007-11-29  MUNDRAPORT     EQ      893.90  909.00   914.75  841.0  887.0   
3  2007-11-30  MUNDRAPORT     EQ      884.20  890.00   958.00  890.0  929.0   
4  2007-12-03  MUNDRAPORT     EQ      921.55  939.75   995.00  922.0  980.0   

    Close    VWAP    Volume      Turnover  Trades  Deliverable Volume  \
0  962.90  984.72  27294366  2.687719e+15     NaN             9859619   
1  893.90  941.38   4581338  4.312765e+14     NaN             1453278   
2  884.20  888.09   5124121  4.550658e+14     NaN             1069678   
3  921.55  929.17   4609762  4.283257e+14     NaN             1260913   
4  969.30  965.65   2977470  2.875200e+14     NaN              816123   

   %Deliverble  
0       0.3612  
1       0.3172  
2       0.2088  
3       0.2735  
4       0.2741

In [ ]:
df.tail()

Date      Symbol Series  Prev Close   Open    High     Low   Last  \
3317  2021-04-26  ADANIPORTS     EQ      725.35  733.0  739.65  728.90  729.2   
3318  2021-04-27  ADANIPORTS     EQ      730.75  735.0  757.50  727.35  748.6   
3319  2021-04-28  ADANIPORTS     EQ      749.15  755.0  760.00  741.10  743.4   
3320  2021-04-29  ADANIPORTS     EQ      746.25  753.2  765.85  743.40  746.4   
3321  2021-04-30  ADANIPORTS     EQ      746.75  739.0  759.45  724.50  726.4   

       Close    VWAP    Volume      Turnover    Trades  Deliverable Volume  \
3317  730.75  733.25   9390549  6.885658e+14  116457.0              838079   
3318  749.15  747.67  20573107  1.538191e+15  236896.0             1779639   
3319  746.25  751.02  11156977  8.379106e+14  130847.0             1342353   
3320  746.75  753.06  13851910  1.043139e+15  153293.0             1304895   
3321  730.05  743.35  12600934  9.366911e+14  132141.0             3514692   

      %Deliverble  
3317       0.0892  
3318       0.0865  
3319       0.1203  
3320       0.0942  
3321       0.2789

In [ ]:
df1=df.reset_index()['Close']

In [ ]:
df1.head()

0    962.90
1    893.90
2    884.20
3    921.55
4    969.30
Name: Close, dtype: float64

In [ ]:
import numpy as np



In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
df1=scaler.fit_transform(np.array(df1).reshape(-1,1))

In [ ]:
df1.shape

(3322, 1)

In [ ]:
training_size=int(len(df1)*0.65)
test_size=len(df1)-training_size
train_data,test_data=df1[0:training_size,:],df1[training_size:len(df1),:1]

In [ ]:
import numpy
def create_dataset(dataset,time_step=1):
  dataX,dataY=[],[]
  for i in range (len(dataset)-time_step-1):
    a=dataset[i:(i+time_step),0]
    dataX.append(a)
    dataY.append(dataset[i+time_step,0])
  return numpy.array(dataX),numpy.array(dataY)

In [ ]:
time_step=100
x_train,y_train=create_dataset(train_data,time_step)
xtest,ytest=create_dataset(test_data,time_step)

In [ ]:
print(x_train)

[[0.71274334 0.65521697 0.64712993 ... 0.44783026 0.46508817 0.46579682]
 [0.65521697 0.64712993 0.67826921 ... 0.46508817 0.46579682 0.46458794]
 [0.64712993 0.67826921 0.71807912 ... 0.46579682 0.46458794 0.50368919]
 ...
 [0.1005044  0.10646546 0.11167618 ... 0.11059235 0.10984201 0.12543249]
 [0.10646546 0.11167618 0.11326024 ... 0.10984201 0.12543249 0.1213056 ]
 [0.11167618 0.11326024 0.10967527 ... 0.12543249 0.1213056  0.12526575]]


In [ ]:
x_train=x_train.reshape(x_train.shape[0],x_train.shape[1],1)
xtest=xtest.reshape(xtest.shape[0],xtest.shape[1],1)

In [ ]:
import tensorflow as tf

# Create a `Sequential` model and add a Dense layer as the first layer.  
model = tf.keras.models.Sequential()
model.add(tf.keras.Input(shape=(16,)))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(256, activation='relu'))
model.add(tf.keras.layers.Dense(256, activation='relu'))
#model.add(tf.keras.layers.Dense(, activation='relu'))
# Now the model will take as input arrays of shape (None, 16)  
# and output arrays of shape (None, 32).  
# Note that after the first layer, you don't need to specify  
# the size of the input anymore:  

model.add(tf.keras.layers.Dense(32))
model.output_shape
model.compile(loss='mean_squared_error',optimizer='adam')

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 32)                544       
                                                                 
 dense_3 (Dense)             (None, 32)                1056      
                                                                 
Total params: 1,600
Trainable params: 1,600
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(x_train,y_train,validation_data=(x_test,ytest),epochs=100,batch_size=64,verbose=1)

Epoch 1/100


ValueError: ignored

In [ ]:
import tensorflow as tf

In [ ]:
in_predict=model.predict()